name: Deploy to AWS ECR

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  push_to_registries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 381492316277.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Build Docker image
        run: docker build -t staging-codese-be .

      - name: Tag Docker image
        run: docker tag staging-codese-be:latest 381492316277.dkr.ecr.ap-southeast-1.amazonaws.com/staging-codese-be:latest

      - name: Push Docker image to ECR
        run: docker push 381492316277.dkr.ecr.ap-southeast-1.amazonaws.com/staging-codese-be:latest